// English UI strings for Darkness Planner
window.DARK_LANG_EN = {
  appSubtitle: 'Location, night date and time/date formats.',
  topHint:
    'Full darkness: astronomical night (Sun below −18°) while the Moon is below the horizon.<br>' +
    'Night: selected date <b>D</b> → <b>D+1</b> (for example, night 29→30).',
  labelLat: 'Latitude, ° (north +)',
  labelLon: 'Longitude, ° (east + / west −)',
  labelStartDate: 'Start date of night',
  btnGeo: 'My location',
  btnCalc: 'Recalculate',
  labelTimeFormat: 'Time format',
  timeFormatHint: '24 hours (off — AM/PM)',
  labelDateFormat: 'Date format',
  labelLanguage: 'Language / Язык',
  filterSubtitle:
    'Filter: find nights where the selected time window has at least the given amount of full darkness.',
  labelFilterFrom: 'Time filter: from',
  labelFilterTo: 'Time filter: to',
  labelFilterDuration: 'Minimum darkness duration, hours',
  labelDowFilter: 'Day-of-week filter',
  dowEmpty: 'Empty (all days)',
  dowFriSat: 'Fri, Sat',
  dowFriSatSun: 'Fri, Sat, Sun',
  dowSatSun: 'Sat, Sun',
  labelDisplayOptions: 'Display',
  filterHideLabel: 'Hide nights that do not pass the filter',
  filterHighlightLabel: 'Highlight nights that pass the filter',
  filterHint:
    'If “Minimum duration” = 0, the time filter is disabled (but day-of-week filter still applies if set).',
  blockDarkTitle: 'Full darkness (selected night)',
  blockSunTitle: 'Sun',
  blockMoonTitle: 'Moon (for this night)',
  blockPhaseTitle: 'Moon phase',
  futureTitle: 'Next 30 nights — full darkness windows',
  thNight: 'Night',
  thDarkness: 'Full darkness',
  thTotal: 'Total duration',
  nightLegend:
    'Column “Night” is the calendar date <b>D</b>, while the night itself is <b>D → D+1</b>.',
  weekendSat: ' (Saturday)',
  weekendSun: ' (Sunday)',
  nightPrefix: 'night ',
  nightHeaderPrefix: 'Night ',
  sunSunset: 'Sunset',
  sunSunrise: 'Sunrise',
  sunAstrStart: 'Astron. night start',
  sunAstrEnd: 'Astron. night end',
  moonBelowAllNight: 'The Moon stays below the horizon all night.',
  moonAboveAllNight: 'The Moon stays above the horizon all night.',
  moonNoEvents: 'No moonrise/moonset within this night.',
  moonRisePrefix: 'Rise: ',
  moonSetPrefix: 'Set: ',
  phaseUnavailable: 'Moon phase unavailable',
  noAstrNight:
    '<span class="warn">No astronomical night (Sun does not go below −18°).</span>',
  noFullDark:
    '<span class="warn">No full darkness (the Moon is up all astronomical night).</span>',
  darkMulti: 'There are several separate full-darkness windows during this night.',
  darkSingle:
    'Between these times the Moon is below the horizon and it is astronomical night.',
  filterNightNoDark: 'This night has no astronomical darkness without the Moon. ',
  filterDayIn: 'Current night is within the selected days of week. ',
  filterDayOut: 'Current night is outside of the selected days of week. ',
  filterTimeOkPrefix: 'In the selected time window there are ',
  filterTimeOkSuffix: ' of darkness (not less than required ',
  filterTimeNotOkPrefix: 'In the selected time window there are only ',
  filterTimeNotOkSuffix: ' of darkness (less than required ',
  filterTimeClose: '). ',
  nextNightPrefix: 'Next suitable night: ',
  nextNightTomorrow: 'tomorrow',
  nextNightAfter: 'the day after tomorrow',
  nextNightInDays: 'in {D} days',
  nextNone: 'No suitable nights found within the next 30 nights.',
  geoNotSupported: 'Geolocation is not supported by this browser.',
  geoFailed: 'Failed to get coordinates.',
  filterAstrStart: 'Astronomical night start',
  filterAstrEnd: 'Astronomical night end',
  versionLabel: 'Darkness Planner · v1.35'
};
